// import { useEffect } from 'react'
import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar'
import { GameView } from '../components/GameView'

const Home: NextPage = () => {
  // const styleObject = {}
  // useEffect(() => {
  //   styleObject.height = window.innerHeight

  // }, [])

  return (
    <div className="bg-slate-900 light:bg-white min-h-full text-white light:text-black">
      <Head>
        <title>Endless Wordle Clone Deutsch</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`flex flex-col items-center min-h-full overflow-y-hidden absolute inset-0`}>
        <Navbar />
        <GameView />
      </main>
    </div>
  )
}

export default Home
