import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Navbar from '../components/navbar'
import { GameView } from '../components/GameView'

const Home: NextPage = () => {
  return (
    <div className="bg-slate-900 light:bg-white text-white light:text-black">
      <Head>
        <title>Woortel :)</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1, user-scalable=no"></meta>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <main className={styles.main}>
        <GameView />
      </main>
    </div>
  )
}

export default Home
